baseURL = "https://shio-chan-dev.github.io/jeanblog/"
languageCode = "zh-cn"
title = "Jeanphilo Blog"
theme = "PaperMod"

pagination.pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"


[outputs]
home = ["HTML", "RSS", "JSON"]   # JSON 用于搜索

[params]
  env = "production"
  defaultTheme = "auto"         # 自动切换深色/浅色
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showToc = true
  showCodeCopyButtons = true
  showAllPostsArchive = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 20

  [[menu.main]]
    identifier = "cat-linux"
    name = "Linux"
    url = "/categories/linux/"
    weight = 30

  [[menu.main]]
    identifier = "cat-python"
    name = "Python"
    url = "/categories/python/"
    weight = 40

  [[menu.main]]
    identifier = "cat-leetcode"
    name = "leetcode"
    url = "/categories/leetcode/"
    weight = 50

