baseURL = "https://shio-chan-dev.github.io/jeanblog/"
languageCode = "zh-cn"
title = "Jeanphilo Blog"

pagination.pagerSize = 10

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"


[languages]
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-cn"
    weight = 1
    contentDir = "content/zh"
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2
    contentDir = "content/en"

[taxonomies]
  category = "categories"
  tag = "tags"


[outputs]
home = ["HTML", "RSS", "JSON"]   # JSON 用于搜索

[params]
  env = "production"
  defaultTheme = "auto"         # 自动切换深色/浅色
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showToc = true
  showCodeCopyButtons = true
  showAllPostsArchive = true
  mainSections = ["notes", "dev", "ai", "linux", "alg", "thoughts"]

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/JeanphiloGong"

  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/Jeanphilo"

[languages.zh.menu]
  [[languages.zh.menu.main]]
    identifier = "archives"
    name = "归档"
    pageRef = "archives"
    weight = 10

  [[languages.zh.menu.main]]
    identifier = "dev"
    name = "开发"
    pageRef = "dev"
    weight = 20

  [[languages.zh.menu.main]]
    identifier = "ai"
    name = "AI"
    pageRef = "ai"
    weight = 25

  [[languages.zh.menu.main]]
    identifier = "alg"
    name = "算法"
    pageRef = "alg"
    weight = 30

  [[languages.zh.menu.main]]
    identifier = "search"
    name = "搜索"
    pageRef = "search"
    weight = 40

  [[languages.zh.menu.main]]
    identifier = "categories"
    name = "分类"
    pageRef = "categories"
    weight = 50

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "archives"
    name = "Archives"
    pageRef = "archives"
    weight = 10

  [[languages.en.menu.main]]
    identifier = "dev"
    name = "Dev"
    pageRef = "dev"
    weight = 20

  [[languages.en.menu.main]]
    identifier = "alg"
    name = "Algorithms"
    pageRef = "alg"
    weight = 30

  [[languages.en.menu.main]]
    identifier = "search"
    name = "Search"
    pageRef = "search"
    weight = 40

  [[languages.en.menu.main]]
    identifier = "categories"
    name = "Categories"
    pageRef = "categories"
    weight = 50
