baseURL = "https://shio-chan-dev.github.io/jeanblog/"
languageCode = "zh-cn"
title = "Jeanphilo Blog"
theme = "PaperMod"

pagination.pagerSize = 10

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-cn"
    weight = 1
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"


[outputs]
home = ["HTML", "RSS", "JSON"]   # JSON 用于搜索

[params]
  env = "production"
  defaultTheme = "auto"         # 自动切换深色/浅色
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showToc = true
  showCodeCopyButtons = true
  showAllPostsArchive = true

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/JeanphiloGong"

  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/Jeanphilo"

[languages.zh.menu]
  [[languages.zh.menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10

  [[languages.zh.menu.main]]
    identifier = "dev"
    name = "开发"
    url = "/dev/"
    weight = 20

  [[languages.zh.menu.main]]
    identifier = "alg"
    name = "算法"
    url = "/alg/"
    weight = 30

  [[languages.zh.menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 40

  [[languages.zh.menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 50

  [[languages.zh.menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 60

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/en/archives/"
    weight = 10

  [[languages.en.menu.main]]
    identifier = "dev"
    name = "Dev"
    url = "/en/dev/"
    weight = 20

  [[languages.en.menu.main]]
    identifier = "alg"
    name = "Algorithms"
    url = "/en/alg/"
    weight = 30

  [[languages.en.menu.main]]
    identifier = "search"
    name = "Search"
    url = "/en/search/"
    weight = 40

  [[languages.en.menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/en/categories/"
    weight = 50

  [[languages.en.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/en/tags/"
    weight = 60
